name: KaryPlugin
version: '${project.version}'
main: com.kary.karyplugin.KaryPlugin
api-version: '1.20'
commands:
  joinGame:
    usage: /<command>
    permission: joinGame.use
  quitMatching:
    usage: /<command>
    permission: quitMatching.use
