name: KaryPlugin
version: '${project.version}'
main: com.kary.karyplugin.KaryPlugin
api-version: '1.20'
commands:
  brawl:
    usage: /<command>
  soloPVP:
    usage: /<command>
  quitMatching:
    usage: /<command>
  testDatabase:
    usage: /<command>
