name: KaryPlugin
version: '${project.version}'
main: com.kary.karyplugin.KaryPlugin
api-version: '1.20'
commands:
  brawl:
    usage: /<command>
    permission: joinGame.use
  soloPVP:
    usage: /<command>
    permission: joinGame.use
  quitMatching:
    usage: /<command>
    permission: quitMatching.use
  testDatabase:
    usage: /<command>
    permission: testDatabase.use
