name: KaryPlugin
version: '1.0-SNAPSHOT'
libraries:
  - org.mybatis:mybatis:3.5.6
  - mysql:mysql-connector-java:8.0.31
  - junit:junit:4.12
main: com.kary.karyplugin.KaryPlugin
api-version: '1.20'
commands:
  brawl:
    usage: /<command>
  soloPVP:
    usage: /<command>
  quitMatching:
    usage: /<command>
  testDatabase:
    usage: /<command>
